# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'kafka-producer'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: kafka-jmx-metrics
    static_configs:
       - targets: ['localhost:7071']