{
 "title": "Kafka_Producer_Consumer",
 "time": { "from": "2021-04-28T11:03:17.739Z", "to": "2021-04-28T13:32:09.631Z" },
 "panels": [
  { "title": "Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batch size avg",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "batch_size_avg{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Request latency avg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_latency_avg{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Batch size avg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "batch_size_avg{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Batch size max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "batch_size_max{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Bytes consumed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bytes_consumed_rate{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Fetch rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fetch_rate{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Records lag max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "records_lag_max{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}",
     "legendFormat": "records_lag_max"
    }
   ]
  }
 ]
}