{
 "title": "Kafka",
 "time": { "from": "2021-04-28T11:03:17.739Z", "to": "2021-04-28T13:32:09.631Z" },
 "panels": [
  {
   "title": "Broker Metrics (Kafka-emitted)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Shows how many Brokers are active controllers.",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_controller_KafkaController_ActiveControllerCount"
      }
     ]
    },
    {
     "title": "Offline Replica Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_controller_KafkaController_OfflinePartitionsCount"
      }
     ]
    },
    {
     "title": "Failed Requests (last hour)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "increase(kafka_server_BrokerTopicMetrics_FailedProduceRequests_total[1h])"
      }
     ]
    },
    {
     "title": "Bytes In / Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kafka_server_BrokerTopicMetrics_BytesIn_total{topic=\"topic_Covid\"}[1m])/1000000",
       "legendFormat": "Total Megabyte In"
      },
      {
       "expr": "increase(kafka_server_BrokerTopicMetrics_BytesOut_total{topic=\"topic_Covid\"}[1m])/1000000",
       "legendFormat": "Total Megabyte Out"
      }
     ]
    },
    {
     "title": "Requests per Minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"Produce\"}[1m])",
       "legendFormat": "Produce"
      },
      {
       "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"FetchConsumer\"}[1m])",
       "legendFormat": "Fetch Consumer"
      },
      {
       "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"FetchFollower\"}[1m])",
       "legendFormat": "Fetch Follower"
      }
     ]
    },
    {
     "title": "Fetch Consumer",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 12 },
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.95\", request=\"FetchConsumer\"}",
       "legendFormat": "Produce Reqeust"
      }
     ]
    },
    {
     "title": "Produce",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 15 },
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.95\", request=\"Produce\"}",
       "legendFormat": "Produce Reqeust"
      }
     ]
    },
    {
     "title": "Fetch Follower",
     "type": "gauge",
     "gridPos": { "h": 3, "w": 4, "x": 18, "y": 18 },
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.95\", request=\"FetchFollower\"}",
       "legendFormat": "Produce Reqeust"
      }
     ]
    }
   ]
  },
  { "title": "Broker Metrics (Host Usage)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Broker Metrics (JVM garbage collection metrics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  { "title": "Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Consumer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  }
 ]
}