{
 "title": "Kafka",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Broker Metrics (Kafka-emitted)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Shows how many Brokers are active controllers.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_ActiveControllerCount"
    }
   ]
  },
  {
   "title": "Offline Replica Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_OfflinePartitionsCount"
    }
   ]
  },
  {
   "title": "Failed Requests (last hour)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_FailedProduceRequests_total[1h])"
    }
   ]
  },
  {
   "title": "Fetch Consumer",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.75\", request=\"FetchConsumer\"}",
     "legendFormat": "Produce Reqeust"
    }
   ]
  },
  {
   "title": "Bytes In / Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_BytesIn_total{topic!=\"\"}[1m])/1000000",
     "legendFormat": "Total Megabyte In {{topic}}"
    },
    {
     "expr": "increase(kafka_server_BrokerTopicMetrics_BytesOut_total{topic!=\"\"}[1m])/1000000",
     "legendFormat": "Total Megabyte Out {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Follower",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.95\", request=\"FetchFollower\"}",
     "legendFormat": "Produce Reqeust"
    }
   ]
  },
  {
   "title": "Produce",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_TotalTimeMs{quantile=\"0.95\", request=\"Produce\"}",
     "legendFormat": "Produce Reqeust"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"Produce\"}[1m])",
     "legendFormat": "Produce"
    },
    {
     "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"FetchConsumer\"}[1m])",
     "legendFormat": "Fetch Consumer"
    },
    {
     "expr": "increase(kafka_network_RequestMetrics_Requests_total{request=\"FetchFollower\"}[1m])",
     "legendFormat": "Fetch Follower"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Replicas per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_topic_partition_replicas{topic!=\"__consumer_offsets\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset[5m])/5)",
     "legendFormat": "Message in per minute"
    }
   ]
  },
  {
   "title": "Request latency avg",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_latency_avg{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Batch size avg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "batch_size_avg{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  {
   "title": "Batch size max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "batch_size_max{instance=\"host.docker.internal:8000\", job=\"kafka-producer\"}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_lag)",
     "legendFormat": "Group: {{consumergroup}}"
    }
   ]
  }
 ]
}